# Generated by Django 6.0.6 on 2026-06-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=11)),
                ('overdraft', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('credit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('type', models.CharField(choices=[('current', 'Courant'), ('saving', "Livret d'Epargne")], max_length=10)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
            ],
        ),
    ]
