# Generated by Django 6.0.6 on 2026-06-26 08:48

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_user_alter_account_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('purchase', 'Achat'), ('transfer', 'Virement')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='client.account')),
            ],
        ),
    ]
