# Generated by Django 6.0.6 on 2026-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='addresses',
            field=models.ManyToManyField(related_name='clients', to='client.address'),
        ),
    ]
